import Miniheader from './components/Miniheader'
import './globals.css'
import Header from './components/Header'
import Body from './components/Body'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <Miniheader/>
        {children}
        <Body/>
        </body>
    </html>
  )
}
