import Miniheader from './components/Miniheader'
import './globals.css'
import Header from './components/Header'



export const metadata = {
  title: 'Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <Miniheader/>
        {children}
        
        </body>
    </html>
  )
}
